# Generated by Django 2.2.1 on 2020-07-07 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('att_subscriptions', '0001_initial'),
        ('sprint_subscriptions', '0001_initial'),
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_data', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('price_video', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date', models.DateField(null=True)),
                ('kilobytes_used', models.IntegerField(default=0)),
                ('seconds_used', models.IntegerField(default=0)),
                ('att_subscription_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='att_subscriptions.ATTSubscription')),
                ('sprint_subscription_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sprint_subscriptions.SprintSubscription')),
            ],
        ),
    ]
