# Generated by Django 2.2.1 on 2020-07-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0002_usagerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagerecord',
            name='price_data',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usagerecord',
            name='price_video',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
