# Generated by Django 2.2.1 on 2020-07-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0003_auto_20200707_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usagerecord',
            old_name='price_video',
            new_name='price_voice',
        ),
    ]
